// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokMultiasset, StoryblokRichtext, StoryblokAsset, StoryblokMultilink } from '../storyblok.d.ts';
export interface Article {
  pagetitle?: string;
  pageintro?: string;
  date: string;
  headerpicture?: StoryblokAsset;
  teaser?: unknown;
  teasertitle?: string;
  teaserimage?: StoryblokAsset;
  readmoretext?: string;
  abstract?: string;
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "article";
  _uid: string;
  [k: string]: unknown;
}

export interface Articleteaserlist {
  type: "" | "automatic" | "manual";
  folder?: string;
  limit: string;
  articles?: (ISbStoryData<Article> | string)[];
  layout: "" | "small" | "wide";
  component: "articleteaserlist";
  _uid: string;
  [k: string]: unknown;
}

export interface Blog {
  pagetitle?: string;
  pageintro?: string;
  date: string;
  headerpicture?: StoryblokAsset;
  teaser?: unknown;
  teasertitle?: string;
  teaserimage?: StoryblokAsset;
  readmoretext?: string;
  abstract?: string;
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "blog";
  _uid: string;
  [k: string]: unknown;
}

export interface Divider {
  component: "divider";
  _uid: string;
  [k: string]: unknown;
}

export interface Gallery {
  layout: "" | "default";
  images?: StoryblokMultiasset;
  title?: string;
  columns: string;
  component: "gallery";
  _uid: string;
  [k: string]: unknown;
}

export interface Globalsettings {
  copyright?: string;
  avatar?: StoryblokAsset;
  topnav: (ISbStoryData<Page> | string)[];
  footernav?: (ISbStoryData<Page> | string)[];
  component: "globalsettings";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid2Column {
  col1?: (
    | Article
    | Articleteaserlist
    | Blog
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  col2?: (
    | Article
    | Articleteaserlist
    | Blog
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "grid_2column";
  _uid: string;
  [k: string]: unknown;
}

export interface Grouping {
  grouptitle: string;
  groupcontent?: (
    | Article
    | Articleteaserlist
    | Blog
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "grouping";
  _uid: string;
  [k: string]: unknown;
}

export interface Hyperlink {
  url: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label: string;
  component: "hyperlink";
  _uid: string;
  [k: string]: unknown;
}

export interface Icon {
  svg?: string;
  component: "icon";
  _uid: string;
  [k: string]: unknown;
}

export interface Linklist {
  style?: "" | "icon" | "icontext";
  links?: (ISbStoryData<Sociallink> | string)[];
  component: "linklist";
  _uid: string;
  [k: string]: unknown;
}

export interface LuxarisePicture {
  pic_thumb?: StoryblokAsset;
  abstract: string;
  name: string;
  title: string;
  pic_big?: StoryblokAsset;
  etsy_url?: string;
  tags?: string;
  socialmedia?: boolean;
  etsy?: boolean;
  gelato?: boolean;
  WhiteWall?: boolean;
  gelato_id?: string;
  component: "luxarise_picture";
  _uid: string;
  [k: string]: unknown;
}

export interface LuxarisePictureSlideshow {
  pictures: (ISbStoryData<LuxarisePicture> | string)[];
  spacing?: "" | "default" | "large";
  component: "luxarise_picture_slideshow";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  pagetitle?: string;
  pageintro?: string;
  layout: "" | "wide" | "narrow" | "home";
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  hidepagetitle?: boolean;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Pagetitle {
  pagetitle?: string;
  pageintro?: string;
  component: "pagetitle";
  _uid: string;
  [k: string]: unknown;
}

export interface Photos {
  images?: StoryblokMultiasset;
  component: "photos";
  _uid: string;
  [k: string]: unknown;
}

export interface Picture {
  image?: StoryblokAsset;
  style?: "" | "normal" | "keyvisual" | "small";
  spacing: "" | "default" | "large";
  component: "picture";
  _uid: string;
  [k: string]: unknown;
}

export interface Richtext {
  content?: StoryblokRichtext;
  component: "richtext";
  _uid: string;
  [k: string]: unknown;
}

export interface Sociallink {
  url: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  text: string;
  icon: ISbStoryData<Icon> | string;
  component: "sociallink";
  _uid: string;
  [k: string]: unknown;
}

export interface Soundcloud {
  title?: string;
  soundcloudid?: string;
  url?: string;
  component: "soundcloud";
  _uid: string;
  [k: string]: unknown;
}

export interface Stuff {
  pagetitle?: string;
  pageintro?: string;
  shortabstact: string;
  headerpicture?: StoryblokAsset;
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  Teaser?: unknown;
  teasertitle?: string;
  abstract?: string;
  readmoretext?: string;
  teaserimage?: StoryblokAsset;
  component: "stuff";
  _uid: string;
  [k: string]: unknown;
}

export interface Stuffteaserlist {
  stuffs?: (ISbStoryData<Stuff> | string)[];
  layout: "" | "big" | "small";
  component: "stuffteaserlist";
  _uid: string;
  [k: string]: unknown;
}

export interface Tool {
  title: string;
  description?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "tool";
  _uid: string;
  [k: string]: unknown;
}

export interface Video {
  file?: StoryblokAsset;
  component: "video";
  _uid: string;
  [k: string]: unknown;
}

export interface Youtube {
  youtubeid?: string;
  format: "" | "cinema" | "square";
  component: "youtube";
  _uid: string;
  [k: string]: unknown;
}
