// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData, SbBlokKeyDataTypes } from '@storyblok/js';
import type { StoryblokMultiasset, StoryblokRichtext, StoryblokAsset, StoryblokMultilink } from '../storyblok.d.ts';
export interface Article {
  pagetitle?: string;
  pageintro?: string;
  date: string;
  headerpicture?: StoryblokAsset;
  teaser?: unknown;
  teasertitle?: string;
  teaserimage?: StoryblokAsset;
  readmoretext?: string;
  abstract?: string;
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Blogteaserlist
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "article";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Articleteaserlist {
  type: "" | "automatic" | "manual";
  folder?: string;
  limit: string;
  articles?: (ISbStoryData<Article> | string)[];
  layout: "" | "small" | "wide";
  component: "articleteaserlist";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Blog {
  pagetitle?: string;
  pageintro?: string;
  date: string;
  headerpicture?: StoryblokAsset;
  teaser?: unknown;
  teasertitle?: string;
  teaserimage?: StoryblokAsset;
  readmoretext?: string;
  abstract?: string;
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Blogteaserlist
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "blog";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Blogteaserlist {
  type: "" | "automatic" | "manual";
  folder?: string;
  limit: string;
  articles?: (ISbStoryData<Blog> | string)[];
  layout: "" | "small" | "wide";
  component: "blogteaserlist";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Divider {
  component: "divider";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Gallery {
  layout: "" | "default";
  images?: StoryblokMultiasset;
  title?: string;
  columns: string;
  component: "gallery";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Globalsettings {
  copyright?: string;
  avatar?: StoryblokAsset;
  topnav: (ISbStoryData<Page> | string)[];
  footernav?: (ISbStoryData<Page> | string)[];
  component: "globalsettings";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Grid2Column {
  col1?: (
    | Article
    | Articleteaserlist
    | Blog
    | Blogteaserlist
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  col2?: (
    | Article
    | Articleteaserlist
    | Blog
    | Blogteaserlist
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "grid_2column";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Grouping {
  grouptitle: string;
  groupcontent?: (
    | Article
    | Articleteaserlist
    | Blog
    | Blogteaserlist
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  component: "grouping";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Hyperlink {
  url: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label: string;
  component: "hyperlink";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Icon {
  svg?: string;
  component: "icon";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Linklist {
  style?: "" | "icon" | "icontext";
  links?: (ISbStoryData<Sociallink> | string)[];
  component: "linklist";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface LuxarisePicture {
  pic_thumb?: StoryblokAsset;
  abstract: string;
  name: string;
  title: string;
  pic_big?: StoryblokAsset;
  etsy_url?: string;
  tags?: string;
  socialmedia?: boolean;
  etsy?: boolean;
  gelato?: boolean;
  WhiteWall?: boolean;
  gelato_id?: string;
  component: "luxarise_picture";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface LuxarisePictureSlideshow {
  pictures: (ISbStoryData<LuxarisePicture> | string)[];
  spacing?: "" | "default" | "large";
  component: "luxarise_picture_slideshow";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Page {
  pagetitle?: string;
  pageintro?: string;
  layout: "" | "wide" | "narrow" | "home";
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Blogteaserlist
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  hidepagetitle?: boolean;
  component: "page";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Pagetitle {
  pagetitle?: string;
  pageintro?: string;
  component: "pagetitle";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Photos {
  images?: StoryblokMultiasset;
  component: "photos";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Picture {
  image?: StoryblokAsset;
  style?: "" | "normal" | "keyvisual" | "small";
  spacing: "" | "default" | "large";
  component: "picture";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Richtext {
  content?: StoryblokRichtext;
  component: "richtext";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Sociallink {
  url: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  text: string;
  icon: ISbStoryData<Icon> | string;
  component: "sociallink";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Soundcloud {
  title?: string;
  soundcloudid?: string;
  url?: string;
  component: "soundcloud";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Stuff {
  pagetitle?: string;
  pageintro?: string;
  shortabstact: string;
  headerpicture?: StoryblokAsset;
  body?: (
    | Article
    | Articleteaserlist
    | Blog
    | Blogteaserlist
    | Divider
    | Gallery
    | Globalsettings
    | Grid2column
    | Grouping
    | Hyperlink
    | Icon
    | Linklist
    | LuxarisePicture
    | LuxarisePictureSlideshow
    | Page
    | Pagetitle
    | Photos
    | Picture
    | Richtext
    | Sociallink
    | Soundcloud
    | Stuff
    | Stuffteaserlist
    | Tool
    | Video
    | Youtube
  )[];
  Teaser?: unknown;
  teasertitle?: string;
  abstract?: string;
  readmoretext?: string;
  teaserimage?: StoryblokAsset;
  component: "stuff";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Stuffteaserlist {
  stuffs?: (ISbStoryData<Stuff> | string)[];
  layout: "" | "big" | "small";
  component: "stuffteaserlist";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Tool {
  title: string;
  description?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "tool";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Video {
  file?: StoryblokAsset;
  component: "video";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

export interface Youtube {
  youtubeid?: string;
  format: "" | "cinema" | "square";
  component: "youtube";
  [k: string]: SbBlokKeyDataTypes;
  _uid: string;
}

// Type aliases with "Storyblok" suffix for compatibility
export type ArticleStoryblok = Article
export type ArticleteaserlistStoryblok = Articleteaserlist
export type BlogStoryblok = Blog
export type BlogteaserlistStoryblok = Blogteaserlist
export type DividerStoryblok = Divider
export type GalleryStoryblok = Gallery
export type GlobalsettingsStoryblok = Globalsettings
export type Grid2ColumnStoryblok = Grid2Column
export type GroupingStoryblok = Grouping
export type HyperlinkStoryblok = Hyperlink
export type IconStoryblok = Icon
export type LinklistStoryblok = Linklist
export type LuxarisePictureStoryblok = LuxarisePicture
export type LuxarisePictureSlideshowStoryblok = LuxarisePictureSlideshow
export type PageStoryblok = Page
export type PagetitleStoryblok = Pagetitle
export type PhotosStoryblok = Photos
export type PictureStoryblok = Picture
export type RichtextStoryblok = Richtext
export type SociallinkStoryblok = Sociallink
export type SoundcloudStoryblok = Soundcloud
export type StuffStoryblok = Stuff
export type StuffteaserlistStoryblok = Stuffteaserlist
export type ToolStoryblok = Tool
export type VideoStoryblok = Video
export type YoutubeStoryblok = Youtube

// Storyblok base types
export type AssetStoryblok = StoryblokAsset
export type MultiassetStoryblok = StoryblokMultiasset

// Re-export Storyblok types for convenience
export type { StoryblokAsset, StoryblokMultiasset, StoryblokRichtext, StoryblokMultilink }
