// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}

export interface ArticleStoryblok {
  pagetitle?: string;
  pageintro?: string;
  date: string;
  headerpicture?: AssetStoryblok;
  teaser?: any;
  teasertitle?: string;
  teaserimage?: AssetStoryblok;
  readmoretext?: string;
  abstract?: string;
  body?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GalleryStoryblok
    | GlobalsettingsStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | HyperlinkStoryblok
    | IconStoryblok
    | LinklistStoryblok
    | PageStoryblok
    | PagetitleStoryblok
    | PhotosStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | SociallinkStoryblok
    | SoundcloudStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
    | ToolStoryblok
    | VideoStoryblok
    | YoutubeStoryblok
  )[];
  component: "article";
  _uid: string;
  [k: string]: any;
}

export interface ArticleteaserlistStoryblok {
  type: "" | "automatic" | "manual";
  folder?: string;
  limit: string;
  articles?: (ISbStoryData<ArticleStoryblok> | string)[];
  layout: "" | "small" | "wide";
  component: "articleteaserlist";
  _uid: string;
  [k: string]: any;
}

export interface DividerStoryblok {
  component: "divider";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}[];

export interface GalleryStoryblok {
  layout: "" | "default";
  images?: MultiassetStoryblok;
  title?: string;
  columns: string;
  component: "gallery";
  _uid: string;
  [k: string]: any;
}

export interface GlobalsettingsStoryblok {
  copyright?: string;
  avatar?: AssetStoryblok;
  topnav: (ISbStoryData<PageStoryblok> | string)[];
  footernav?: (ISbStoryData<PageStoryblok> | string)[];
  component: "globalsettings";
  _uid: string;
  [k: string]: any;
}

export interface Grid2ColumnStoryblok {
  col1?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GalleryStoryblok
    | GlobalsettingsStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | HyperlinkStoryblok
    | IconStoryblok
    | LinklistStoryblok
    | PageStoryblok
    | PagetitleStoryblok
    | PhotosStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | SociallinkStoryblok
    | SoundcloudStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
    | ToolStoryblok
    | VideoStoryblok
    | YoutubeStoryblok
  )[];
  col2?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GalleryStoryblok
    | GlobalsettingsStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | HyperlinkStoryblok
    | IconStoryblok
    | LinklistStoryblok
    | PageStoryblok
    | PagetitleStoryblok
    | PhotosStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | SociallinkStoryblok
    | SoundcloudStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
    | ToolStoryblok
    | VideoStoryblok
    | YoutubeStoryblok
  )[];
  component: "grid_2column";
  _uid: string;
  [k: string]: any;
}

export interface GroupingStoryblok {
  grouptitle: string;
  groupcontent?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GalleryStoryblok
    | GlobalsettingsStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | HyperlinkStoryblok
    | IconStoryblok
    | LinklistStoryblok
    | PageStoryblok
    | PagetitleStoryblok
    | PhotosStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | SociallinkStoryblok
    | SoundcloudStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
    | ToolStoryblok
    | VideoStoryblok
    | YoutubeStoryblok
  )[];
  component: "grouping";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: any;
    };

export interface HyperlinkStoryblok {
  url: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  label: string;
  component: "hyperlink";
  _uid: string;
  [k: string]: any;
}

export interface IconStoryblok {
  svg?: string;
  component: "icon";
  _uid: string;
  [k: string]: any;
}

export interface LinklistStoryblok {
  style?: "" | "icon" | "icontext";
  links?: (ISbStoryData<SociallinkStoryblok> | string)[];
  component: "linklist";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  pagetitle?: string;
  pageintro?: string;
  layout: "" | "wide" | "narrow" | "home";
  body?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GalleryStoryblok
    | GlobalsettingsStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | HyperlinkStoryblok
    | IconStoryblok
    | LinklistStoryblok
    | PageStoryblok
    | PagetitleStoryblok
    | PhotosStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | SociallinkStoryblok
    | SoundcloudStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
    | ToolStoryblok
    | VideoStoryblok
    | YoutubeStoryblok
  )[];
  hidepagetitle?: boolean;
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface PagetitleStoryblok {
  pagetitle?: string;
  pageintro?: string;
  component: "pagetitle";
  _uid: string;
  [k: string]: any;
}

export interface PhotosStoryblok {
  images?: MultiassetStoryblok;
  component: "photos";
  _uid: string;
  [k: string]: any;
}

export interface PictureStoryblok {
  image?: AssetStoryblok;
  style?: "" | "normal" | "keyvisual";
  component: "picture";
  _uid: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  content?: RichtextStoryblok;
  component: "richtext";
  _uid: string;
  [k: string]: any;
}

export interface SociallinkStoryblok {
  url: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  text: string;
  icon: ISbStoryData<IconStoryblok> | string;
  component: "sociallink";
  _uid: string;
  [k: string]: any;
}

export interface SoundcloudStoryblok {
  title?: string;
  soundcloudid?: string;
  url?: string;
  component: "soundcloud";
  _uid: string;
  [k: string]: any;
}

export interface StuffStoryblok {
  pagetitle?: string;
  pageintro?: string;
  shortabstact: string;
  headerpicture?: AssetStoryblok;
  body?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GalleryStoryblok
    | GlobalsettingsStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | HyperlinkStoryblok
    | IconStoryblok
    | LinklistStoryblok
    | PageStoryblok
    | PagetitleStoryblok
    | PhotosStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | SociallinkStoryblok
    | SoundcloudStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
    | ToolStoryblok
    | VideoStoryblok
    | YoutubeStoryblok
  )[];
  Teaser?: any;
  teasertitle?: string;
  abstract?: string;
  readmoretext?: string;
  teaserimage?: AssetStoryblok;
  component: "stuff";
  _uid: string;
  [k: string]: any;
}

export interface StuffteaserlistStoryblok {
  stuffs?: (ISbStoryData<StuffStoryblok> | string)[];
  layout: "" | "big" | "small";
  component: "stuffteaserlist";
  _uid: string;
  [k: string]: any;
}

export interface ToolStoryblok {
  title: string;
  description?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "tool";
  _uid: string;
  [k: string]: any;
}

export interface VideoStoryblok {
  file?: AssetStoryblok;
  component: "video";
  _uid: string;
  [k: string]: any;
}

export interface YoutubeStoryblok {
  youtubeid?: string;
  component: "youtube";
  _uid: string;
  [k: string]: any;
}
