// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}

export interface ArticleStoryblok {
  slug?: string;
  title?: string;
  abstract?: string;
  date?: string;
  teaserimage?: AssetStoryblok;
  readmoretext?: string;
  content?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GlobalStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | LinkStoryblok
    | PageStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
  )[];
  component: "article";
  _uid: string;
  [k: string]: any;
}

export interface ArticleteaserlistStoryblok {
  component: "articleteaserlist";
  _uid: string;
  [k: string]: any;
}

export interface DividerStoryblok {
  component: "divider";
  _uid: string;
  [k: string]: any;
}

export interface GlobalStoryblok {
  copyright?: string;
  avatar?: AssetStoryblok;
  topnav?: any[];
  footernav?: any[];
  component: "global";
  _uid: string;
  [k: string]: any;
}

export interface Grid2ColumnStoryblok {
  col1?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GlobalStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | LinkStoryblok
    | PageStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
  )[];
  col2?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GlobalStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | LinkStoryblok
    | PageStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
  )[];
  component: "grid_2column";
  _uid: string;
  [k: string]: any;
}

export interface GroupingStoryblok {
  grouptitle?: string;
  groupcontent?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GlobalStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | LinkStoryblok
    | PageStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
  )[];
  component: "grouping";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: any;
    };

export interface LinkStoryblok {
  url?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  text?: string;
  title?: string;
  icon?: AssetStoryblok;
  component: "link";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GlobalStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | LinkStoryblok
    | PageStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
  )[];
  slug: string;
  title: string;
  description?: string;
  layout: "" | "wide" | "narrow";
  pageheadline: string;
  pageintro: string;
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface PictureStoryblok {
  image?: AssetStoryblok;
  style?: "" | "normal" | "keyvisual";
  component: "picture";
  _uid: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  content?: RichtextStoryblok;
  component: "richtext";
  _uid: string;
  [k: string]: any;
}

export interface StuffStoryblok {
  slug?: string;
  title?: string;
  abstract?: string;
  date?: string;
  teaserimage?: AssetStoryblok;
  readmoretext?: string;
  content?: (
    | ArticleStoryblok
    | ArticleteaserlistStoryblok
    | DividerStoryblok
    | GlobalStoryblok
    | Grid2ColumnStoryblok
    | GroupingStoryblok
    | LinkStoryblok
    | PageStoryblok
    | PictureStoryblok
    | RichtextStoryblok
    | StuffStoryblok
    | StuffteaserlistStoryblok
  )[];
  component: "stuff";
  _uid: string;
  [k: string]: any;
}

export interface StuffteaserlistStoryblok {
  stuffs?: (ISbStoryData<StuffStoryblok> | string)[];
  component: "stuffteaserlist";
  _uid: string;
  [k: string]: any;
}
