import type { Metadata } from 'next'
import { Layout } from '@/components/spotlight/Layout.tsx'
import { Providers } from '@/components/providers.tsx'
import { StoryblokProvider } from '@/provider'
import '@/styles/tailwind.css'


export const revalidate = 0
export const fetchCache = 'force-no-store'

export const metadata: Metadata = {
	title: 'Storyblok - Next15 - Tailwindcss',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<StoryblokProvider>
			<html lang="en" className="h-full antialiased" suppressHydrationWarning>
			<body className="flex h-full bg-zinc-50 dark:bg-black">
			<Providers>
				<div className="flex w-full">
					<Layout>
						{children}
					</Layout>
				</div>
			</Providers>
			</body>
			</html>
		</StoryblokProvider>
	)
}
